import type { Product, Artist, Feedback } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Earthen Pear Sculpture',
    subheading: 'Hand-thrown ceramic pears',
    price: 10.99,
    category: 'Sculptures',
    artist: 'Nisha Sharma',
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&q=80',
    description: 'A sculpture of Narendra Damodar Das Modi of height 8 feet.',
    inStock: true,
  },
  {
    id: '2',
    name: 'Sunflower Field Painting',
    subheading: 'Western painting with black background',
    price: 24.99,
    category: 'Paintings',
    artist: 'Nisha Sharma',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=400&q=80',
    description: 'A western painting with black background featuring sunflower field.',
    inStock: true,
  },
  {
    id: '3',
    name: 'Watermelon Ceramic Plate',
    subheading: 'Decorative ceramic art',
    price: 14.99,
    category: 'Ceramics',
    artist: 'Abhijeet Sharma',
    imageUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400&q=80',
    description: 'Vivid, hand-painted ceramic plate shaped like a watermelon slice.',
    inStock: true,
  },
  {
    id: '4',
    name: 'Forest Mushroom Piece',
    subheading: 'Natural organic sculpture',
    price: 19.99,
    category: 'Sculptures',
    artist: 'Rohit Kumar Munda',
    imageUrl: 'https://images.unsplash.com/photo-1550159930-40066082a4fc?w=400&q=80',
    description: 'Unique organic sculpture featuring forest mushrooms on a driftwood base.',
    inStock: true,
  },
  {
    id: '5',
    name: 'Botanical Keychain',
    subheading: 'Hand-painted botanical series',
    price: 4.99,
    category: 'Keychains',
    artist: 'Nisha Sharma',
    imageUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=400&q=80',
    description: 'Delicate hand-painted botanical keychain with real pressed flowers encased in resin.',
    inStock: true,
  },
  {
    id: '6',
    name: 'Abstract Red Canvas',
    subheading: 'Bold expressive painting',
    price: 34.99,
    category: 'Paintings',
    artist: 'Abhijeet Sharma',
    imageUrl: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=400&q=80',
    description: 'Bold, abstract expressionist painting with deep reds and charcoal.',
    inStock: true,
  },
  {
    id: '7',
    name: 'Raku Fired Bowl',
    subheading: 'Traditional Japanese ceramic',
    price: 29.99,
    category: 'Ceramics',
    artist: 'Rohit Kumar Munda',
    imageUrl: 'https://images.unsplash.com/photo-1606215958408-8c0a73eb5b57?w=400&q=80',
    description: 'Hand-thrown and raku fired bowl with crackle glaze finish.',
    inStock: true,
  },
  {
    id: '8',
    name: 'Geometric Stone Carving',
    subheading: 'Modern geometric art',
    price: 44.99,
    category: 'Sculptures',
    artist: 'Nisha Sharma',
    imageUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&q=80',
    description: 'Precision-carved geometric stone sculpture with mineral inclusions.',
    inStock: true,
  },
  {
    id: '9',
    name: 'Indigo Textile Wall Art',
    subheading: 'Handwoven hanging piece',
    price: 39.99,
    category: 'Others',
    artist: 'Abhijeet Sharma',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&q=80',
    description: 'Indigo-dyed handwoven textile wall hanging with geometric patterns.',
    inStock: true,
  },
];

export const MOCK_ARTISTS: Artist[] = [
  {
    id: '1',
    name: 'Nisha Sharma',
    specialties: ['Sculptures', 'Ceramics', 'Paintings'],
    bio: 'Award-winning ceramic artist blending classical technique with contemporary vision.',
  },
  {
    id: '2',
    name: 'Abhijeet Sharma',
    specialties: ['Paintings', 'Keychains', 'Others'],
    bio: 'Multidisciplinary artist exploring the intersection of natural materials and modern form.',
  },
  {
    id: '3',
    name: 'Rohit Kumar Munda',
    specialties: ['Sculptures', 'Ceramics'],
    bio: 'Traditional sculptor whose work honors ancestral techniques while pushing boundaries.',
  },
];

export const MOCK_FEEDBACKS: Feedback[] = [
  { id: '1', user: 'Varun', text: '"Every painting is so real"', },
  { id: '2', user: 'Neha', text: '"Sculptures are just wow"', },
  { id: '3', user: 'Arjun', text: '"This is a haven for artists"', },
];

export const CATEGORIES = ['Ceramics', 'Sculptures', 'Paintings', 'Keychains', 'Others'] as const;
